
        <SCRIPT LANGUAGE="JavaScript" SRC="js/daisyWheel.js">
        </SCRIPT>
        <SCRIPT LANGUAGE="JavaScript" SRC="js/typeValidation.js">
        </SCRIPT>
        <SCRIPT LANGUAGE="JavaScript" SRC="js/fadeing.js">
        </SCRIPT>
        <SCRIPT LANGUAGE="JavaScript" SRC="js/xhr.js">
        </SCRIPT>
        <SCRIPT LANGUAGE="JavaScript" SRC="js/formShowHide.js">
        </SCRIPT>
        <SCRIPT LANGUAGE="JavaScript" SRC="js/commonSpecificFunctions.js">
        </SCRIPT>
    </body>
</html>
