<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html>
    <head>
        <title></title>
        <link rel="stylesheet" type="text/css" href="/css/layout.css" />
    </head>
    <body>
        <div id="topTitle" class="transparent menuItem">CTEC3609:<br />Telematics and Web-Based Control Systems</div>
        <div id="topMenu" class="transparent menuItem">
            <div class="menuItem"><a href="auth/registration" onclick="getForm(this); return false;">Register</a></div>
            <div class="menuItem"><a href="auth/signining" onclick="getForm(this); return false;">Login</a></div>
            <div class="menuItem">About</div>
            <br style="clear: both;" />
        </div>
        <br style="clear: both;" />

