<div id="topTitle" class="transparent menuItem">CTEC3609:<br />Telematics and Web-Based Control Systems</div>
<div id="topMenu" class="transparent menuItem">
    <div class="menuItem">Register</div>
    <div class="menuItem">Login</div>
    <div class="menuItem">About</div>
    <br style="clear: both;" />
</div>
<br style="clear: both;" />
<div class="bottomText" id="bottomText">
</div>
<SCRIPT LANGUAGE="JavaScript" SRC="/js/fourohthree.js">
</SCRIPT>
<SCRIPT LANGUAGE="JavaScript" SRC="/js/fadeing.js">
</SCRIPT>
        